import type {
  Amenity,
  BookingPolicy,
  ClubTableBlueprint,
  HotelRoomBlueprint,
  InventoryBlueprint,
  PaymentStrategy,
  RestaurantTableBlueprint,
  Vertical,
} from './types';

const img = (seed: string) => `https://picsum.photos/seed/${seed}/640/420`;
const amenity = (label: string): Amenity => ({
  id: label.toLowerCase().replace(/[^a-z0-9]+/g, '_'),
  label,
});
const policy = (
  kind: BookingPolicy['kind'],
  label: string,
  value?: string | number
): BookingPolicy => ({ id: `${kind}_${label}`.toLowerCase().replace(/[^a-z0-9]+/g, '_'), kind, label, value });

const CURRENCY = 'USD';

// ─── Hotel ────────────────────────────────────────────────────────────────────

const hotelBlueprints: HotelRoomBlueprint[] = [
  {
    id: 'hotel_standard',
    vertical: 'hotel',
    category: 'room',
    type: 'Standard',
    name: 'Standard Room',
    description: 'Comfortable room with a queen bed and workspace.',
    basePrice: 120,
    currency: CURRENCY,
    capacity: 2,
    maxCapacity: 2,
    roomType: 'Standard',
    bedType: 'Queen',
    view: 'City',
    allowedPaymentStrategies: ['pay_at_venue', 'hold_card_authorization'],
    bookingPolicies: [policy('cancellation', '24h Free Cancellation', 24), policy('check_in', '3 PM Check-In', '15:00')],
    amenities: ['Work Desk', 'Wi-Fi', 'Queen Bed'].map(amenity),
    images: [img('hotel-standard-1'), img('hotel-standard-2')],
    accent: '#64748b',
  },
  {
    id: 'hotel_deluxe',
    vertical: 'hotel',
    category: 'room',
    type: 'Deluxe King',
    name: 'Deluxe King',
    description: 'Spacious king room with ocean view and mini bar.',
    basePrice: 220,
    currency: CURRENCY,
    capacity: 2,
    maxCapacity: 3,
    roomType: 'Deluxe',
    bedType: 'King',
    view: 'Ocean',
    allowedPaymentStrategies: ['deposit_50_percent', 'pay_at_venue'],
    bookingPolicies: [policy('cancellation', '24h Free Cancellation', 24), policy('check_in', '3 PM Check-In', '15:00')],
    amenities: ['King Bed', 'Ocean View', 'Mini Bar'].map(amenity),
    images: [img('hotel-deluxe-1'), img('hotel-deluxe-2')],
    accent: '#0ea5e9',
  },
  {
    id: 'hotel_executive',
    vertical: 'hotel',
    category: 'room',
    type: 'Executive Suite',
    name: 'Executive Suite',
    description: 'Suite with balcony, living area and workspace.',
    basePrice: 450,
    currency: CURRENCY,
    capacity: 3,
    maxCapacity: 4,
    roomType: 'Executive Suite',
    bedType: 'King',
    view: 'Ocean',
    allowedPaymentStrategies: ['full_prepayment', 'deposit_50_percent'],
    bookingPolicies: [policy('cancellation', '48h Free Cancellation', 48), policy('check_in', '3 PM Check-In', '15:00')],
    amenities: ['King Bed', 'Ocean View', 'Balcony', 'Mini Bar', 'Work Desk'].map(amenity),
    images: [img('hotel-exec-1'), img('hotel-exec-2')],
    accent: '#6366f1',
  },
  {
    id: 'hotel_presidential',
    vertical: 'hotel',
    category: 'room',
    type: 'Presidential Suite',
    name: 'Presidential Suite',
    description: 'Top-floor suite with panoramic views and butler service.',
    basePrice: 1200,
    currency: CURRENCY,
    capacity: 4,
    maxCapacity: 6,
    roomType: 'Presidential Suite',
    bedType: 'King',
    view: 'Panoramic',
    allowedPaymentStrategies: ['full_prepayment', 'hold_card_authorization'],
    bookingPolicies: [policy('cancellation', '7d Free Cancellation', 168), policy('check_in', '2 PM Check-In', '14:00')],
    amenities: ['King Bed', 'Panoramic View', 'Balcony', 'Mini Bar', 'Living Room', 'Butler Service'].map(amenity),
    images: [img('hotel-pres-1'), img('hotel-pres-2')],
    accent: '#a855f7',
  },
];

// ─── Club ─────────────────────────────────────────────────────────────────────

const clubBlueprints: ClubTableBlueprint[] = [
  {
    id: 'club_main_floor',
    vertical: 'club',
    category: 'club_table',
    type: 'Main Floor Booth',
    name: 'Main Floor Booth',
    description: 'Booth seating with dedicated service on the main floor.',
    basePrice: 1500,
    currency: CURRENCY,
    capacity: 6,
    maxCapacity: 8,
    tier: 'Main Floor',
    minimumSpend: 1500,
    deposit: 500,
    allowedPaymentStrategies: ['deposit_50_percent', 'pay_at_venue'],
    bookingPolicies: [policy('minimum_spend', 'Min. Spend Required', 1500), policy('entry_time', 'Entry by 11:30 PM', '23:30')],
    amenities: ['Dedicated Server', 'Premium Bottle Setup'].map(amenity),
    images: [img('club-main-1'), img('club-main-2')],
    accent: '#0ea5e9',
  },
  {
    id: 'club_dj_pit',
    vertical: 'club',
    category: 'club_table',
    type: 'DJ Pit VIP',
    name: 'DJ Pit VIP',
    description: 'Prime table beside the DJ booth.',
    basePrice: 3000,
    currency: CURRENCY,
    capacity: 8,
    maxCapacity: 10,
    tier: 'DJ Pit',
    minimumSpend: 3000,
    deposit: 1000,
    allowedPaymentStrategies: ['deposit_50_percent', 'full_prepayment'],
    bookingPolicies: [policy('minimum_spend', 'Min. Spend Required', 3000), policy('entry_time', 'Entry by 11:30 PM', '23:30')],
    amenities: ['Dedicated Server', 'Premium Bottle Setup', 'Stage Sightline'].map(amenity),
    images: [img('club-dj-1'), img('club-dj-2')],
    accent: '#eab308',
  },
  {
    id: 'club_mezzanine',
    vertical: 'club',
    category: 'club_table',
    type: 'Raised Mezzanine',
    name: 'Raised Mezzanine',
    description: 'Elevated VIP zone overlooking the stage.',
    basePrice: 5000,
    currency: CURRENCY,
    capacity: 10,
    maxCapacity: 12,
    tier: 'Mezzanine',
    minimumSpend: 5000,
    deposit: 2000,
    allowedPaymentStrategies: ['full_prepayment', 'deposit_50_percent'],
    bookingPolicies: [policy('minimum_spend', 'Min. Spend Required', 5000), policy('dress_code', 'Smart / Upscale')],
    amenities: ['Dedicated Server', 'Premium Bottle Setup', 'Sparkler Presentation', 'Security Escort', 'Stage Sightline'].map(amenity),
    images: [img('club-mezz-1'), img('club-mezz-2')],
    accent: '#f97316',
  },
  {
    id: 'club_owners_box',
    vertical: 'club',
    category: 'club_table',
    type: "Owner's Box",
    name: "Owner's Box",
    description: 'Private, elevated box with the best sightline in the house.',
    basePrice: 8000,
    currency: CURRENCY,
    capacity: 12,
    maxCapacity: 16,
    tier: "Owner's Box",
    minimumSpend: 8000,
    deposit: 3000,
    allowedPaymentStrategies: ['full_prepayment', 'hold_card_authorization'],
    bookingPolicies: [policy('minimum_spend', 'Min. Spend Required', 8000), policy('dress_code', 'Smart / Upscale')],
    amenities: ['Dedicated Server', 'Premium Bottle Setup', 'Sparkler Presentation', 'Security Escort', 'Private Entrance'].map(amenity),
    images: [img('club-owners-1'), img('club-owners-2')],
    accent: '#a855f7',
  },
];

// ─── Restaurant ───────────────────────────────────────────────────────────────

const restaurantBlueprints: RestaurantTableBlueprint[] = [
  {
    id: 'rest_standard_2top',
    vertical: 'restaurant',
    category: 'restaurant_table',
    type: 'Standard 2-Top',
    name: 'Standard 2-Top',
    description: 'Intimate table for two in the main dining room.',
    basePrice: 0,
    currency: CURRENCY,
    capacity: 2,
    maxCapacity: 4,
    seatingArea: 'Main Dining Area',
    turnTimeMinutes: 90,
    allowedPaymentStrategies: ['pay_at_venue'],
    bookingPolicies: [policy('turn_time', '90-Min Turn Limit', 90), policy('hold_buffer', '15-Min Hold Buffer', 15)],
    amenities: ['Power Outlets', 'Window View', 'Quiet Zone'].map(amenity),
    images: [img('rest-2top-1'), img('rest-2top-2')],
    accent: '#0a6c6d',
  },
  {
    id: 'rest_high_top',
    vertical: 'restaurant',
    category: 'restaurant_table',
    type: 'High-Top Bar',
    name: 'High-Top Bar',
    description: 'Elevated bar seating, great for drinks and small plates.',
    basePrice: 0,
    currency: CURRENCY,
    capacity: 2,
    maxCapacity: 4,
    seatingArea: 'Bar Area',
    turnTimeMinutes: 60,
    allowedPaymentStrategies: ['pay_at_venue'],
    bookingPolicies: [policy('turn_time', '60-Min Turn Limit', 60), policy('hold_buffer', '15-Min Hold Buffer', 15)],
    amenities: ['Power Outlets', 'High Chair Space'].map(amenity),
    images: [img('rest-hightop-1'), img('rest-hightop-2')],
    accent: '#0ea5e9',
  },
  {
    id: 'rest_patio',
    vertical: 'restaurant',
    category: 'restaurant_table',
    type: 'Outdoor Patio',
    name: 'Outdoor Patio',
    description: 'Open-air table on the patio, weather permitting.',
    basePrice: 0,
    currency: CURRENCY,
    capacity: 4,
    maxCapacity: 6,
    seatingArea: 'Terrace',
    turnTimeMinutes: 120,
    allowedPaymentStrategies: ['pay_at_venue', 'deposit_50_percent'],
    bookingPolicies: [policy('turn_time', '2-Hour Turn Limit', 120), policy('cancellation', 'Weather Policy')],
    amenities: ['Wheelchair Access', 'Quiet Zone'].map(amenity),
    images: [img('rest-patio-1'), img('rest-patio-2')],
    accent: '#16a34a',
  },
  {
    id: 'rest_chefs_counter',
    vertical: 'restaurant',
    category: 'restaurant_table',
    type: "Chef's Counter",
    name: "Chef's Counter",
    description: 'Front-row seat to the open kitchen with a tasting menu.',
    basePrice: 150,
    currency: CURRENCY,
    capacity: 2,
    maxCapacity: 2,
    seatingArea: 'Chef\u2019s Counter',
    turnTimeMinutes: 150,
    allowedPaymentStrategies: ['full_prepayment', 'deposit_50_percent'],
    bookingPolicies: [policy('turn_time', 'Tasting Menu · 2.5h', 150), policy('cancellation', '48h Free Cancellation', 48)],
    amenities: ['Chef Interaction', 'Wine Pairing', 'Premium Seating'].map(amenity),
    images: [img('rest-chef-1'), img('rest-chef-2')],
    accent: '#f97316',
  },
];

export const BLUEPRINTS: Record<Vertical, InventoryBlueprint[]> = {
  hotel: hotelBlueprints,
  club: clubBlueprints,
  restaurant: restaurantBlueprints,
};

export function blueprintsFor(vertical: Vertical): InventoryBlueprint[] {
  return BLUEPRINTS[vertical] ?? [];
}

export function findBlueprint(
  blueprints: InventoryBlueprint[],
  id: string | undefined
): InventoryBlueprint | undefined {
  if (!id) return undefined;
  return blueprints.find((blueprint) => blueprint.id === id);
}

export function defaultPaymentStrategies(): PaymentStrategy[] {
  return ['pay_at_venue'];
}
